#!/bin/bash
# .bashrc of gr4viton

loadit() {
if [ -f $1 ]; then
    . $1
    echo "Loaded $1"
fi
}

dir_gr4=$HOME'/gr4log/'

loadit_here() {
    _dir_here=$(dirname $0) 
    loadit "$_dir_here$1"
}

loadit_script() {
    _dir=$dir_gr4'/scripts/'
    loadit $_dir$1
}
# ############## LOAD ALIASES AND FUNCTION FILES ###############
dir_here=$(dirname $0) 
# speak synthesis
loadit_script "alias/speak.sh"
# git
loadit_script "alias/git.sh"
loadit_script "alias/centroid.sh"
loadit_script "alias/install.sh"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    os_name="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    os_name="mac"
elif [[ "$OSTYPE" == "cygwin" ]]; then
    # POSIX compatibility layer and Linux environment emulation for Windows
    os_name="cygwin"
elif [[ "$OSTYPE" == "msys" ]]; then
    # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
    os_name="mingw"
elif [[ "$OSTYPE" == "win32" ]]; then
    # I'm not sure this can happen.
    os_name="win32"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
    # ...
    os_name="freebsd"
else
    # Unknown.
    os_name="unknown"
fi

if [[ "$os_name" == "linux" ]]; then
    if [ -f /etc/system-release ]; then
        system_str=$(cat /etc/system-release)
    fi
    echo $system_str
    case "Fedora" in
        *system_str*)
        distribution_name="fedora"
            ;;
    esac
    echo "$distribution_name"
fi 


# prompt line
BRANCH="\$(git_branch)"

export PS1="${BLUE}${BRANCH}${END} ${GREEN}\u ${YELLOW}\W ${DOLLAR}${END} "

# colors
set colored-stats on

# Nice output and secure deletion/moving and verbosity
if [ "$TERM" != "dumb" ]; then
 eval "`dircolors -b`"
 alias ll='ls -l -F -h -X --group-directories-first --color=always --hide=*~'
 alias lla='ls -lA -F -h -X --group-directories-first --color=always'
 alias la='ls -a'
fi
alias grep='grep --color=auto'
alias mkdir='mkdir -p'
alias rm='rm -iv'
alias cp='cp -vR'

# Handy directory aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# handy extract function for various archives
extract () {
 if [ -f $1 ] ; then
 case $1 in
 *.tar.bz2) tar xjf $1 ;;
 *.tar.gz) tar xzf $1 ;;
 *.bz2) bunzip2 $1 ;;
 *.rar) rar x $1 ;;
 *.gz) gunzip $1 ;;
 *.tar) tar xf $1 ;;
 *.tbz2) tar xjf $1 ;;
 *.tgz) tar xzf $1 ;;
 *.zip) unzip $1 ;;
 *.Z) uncompress $1 ;;
 *.7z) 7z x $1 ;;
 *) echo "'$1' cannot be extracted via extract()" ;;
 esac
 else
 echo "'$1' is not a valid file"
 fi
}

alias vircvim='vim '$home'.vimrc' 
alias vircbash='vim '$rcbash

# logs
alias v1='vim -O '$rcbash' '$gr4env
alias v2='cd '$dirgr4log';vim -O '$dirgr4log'gr4log.vim '$dirkiwilog'kiwi\ log.vim '$logAutomateMe
alias v3='vim -O '$dirgr4log'LOG/nix/logFedora.vim '$dirgr4log


# ############## gr4log

# gr4log
dirgr4log=$HOME'/gr4log/'
dir_gr4scripts="$HOME/gr4log/scripts"
alias gr4log='vim '$dirgr4log'gr4log.vim'
alias gr4log_sync=$dirgr4log'gr4log_git_update.sh'
alias cdgr4log='cd '$dirgr4log

alias vgr4='vim -O bashrc alias/git.sh ~/.bashrc'
alias vgrc='cd $dir_gr4scripts && vgr4'

alias log='cdgr4log;gr4log'
# sync all
alias sync_all='gr4log_sync'


echo "gr4log .bashrc loaded!"
